import os
pAccountName = 'model\\'+'TMobile' #model Name 
pTh = 0.3 # Thershold below intent is categorzied other
pDesc = 'Ticket_Description' # Ticket Description column name for training and testing
pRootDir = 'C:\\Users\\tamohant\\Desktop\\Auto_synthesis_Training_data\\AutoSynthesisLite\\data' # Directory of the data file
pLevel1 = 'Level1' # Column name of Level1
pLevel2 = 'Level2' # column name of Level2
pTrainingFileName = 'TrainData' # name for training file
pTestFileName = 'TestData' # name for testing file
pTrainDir = os.path.join(pRootDir,'inputtraindata') # Training file directory
pTestDir = os.path.join(pRootDir,'inputtestdata') # Testing file Directory
Train = True # Boolean whether to run the script for training or not
Test = True # Boolean whether to run scrip for testing of not 
sim = True # Boolean whether to run scrip for Similarity or not
pTicketId = 'Ticket_No' # colum name for ticket column
preprocessing = True
nTickets = 5
Idx = [100,120,150,300] # Row no. to display for keyword weightage
viz = True #Boolean whether to run the script of visualization
nTopKeywrd = 10 #Top keywords to represent in weight calculation for an intent
pTrainingDataDir = os.path.join(pRootDir  + '\\' + 'traindata' + '\\' + str(pAccountName[6:]))
pThSim = 0.90